default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: May_development

test:
  <<: *default
  database: May_test

production:
  <<: *default
  database: May_production
  username: May
  password: <%= ENV['MAY_DATABASE_PASSWORD'] %>
